package com.kholodkov.coinmonitor.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4C662B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCDEDA3)
val onPrimaryContainerLight = Color(0xFF354E16)
val secondaryLight = Color(0xFF6E5D0E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFAE287)
val onSecondaryContainerLight = Color(0xFF544600)
val tertiaryLight = Color(0xFF006A65)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9DF1EB)
val onTertiaryContainerLight = Color(0xFF00504C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9FAEF)
val onBackgroundLight = Color(0xFF1A1C16)
val surfaceLight = Color(0xFFF9FAEF)
val onSurfaceLight = Color(0xFF1A1C16)
val surfaceVariantLight = Color(0xFFE1E4D5)
val onSurfaceVariantLight = Color(0xFF44483D)
val outlineLight = Color(0xFF75796C)
val outlineVariantLight = Color(0xFFC5C8BA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F312A)
val inverseOnSurfaceLight = Color(0xFFF1F2E6)
val inversePrimaryLight = Color(0xFFB1D18A)
val surfaceDimLight = Color(0xFFDADBD0)
val surfaceBrightLight = Color(0xFFF9FAEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F4E9)
val surfaceContainerLight = Color(0xFFEEEFE3)
val surfaceContainerHighLight = Color(0xFFE8E9DE)
val surfaceContainerHighestLight = Color(0xFFE2E3D8)

val primaryDark = Color(0xFFB1D18A)
val onPrimaryDark = Color(0xFF1F3701)
val primaryContainerDark = Color(0xFF354E16)
val onPrimaryContainerDark = Color(0xFFCDEDA3)
val secondaryDark = Color(0xFFDCC66E)
val onSecondaryDark = Color(0xFF3A3000)
val secondaryContainerDark = Color(0xFF544600)
val onSecondaryContainerDark = Color(0xFFFAE287)
val tertiaryDark = Color(0xFF80D5CF)
val onTertiaryDark = Color(0xFF003734)
val tertiaryContainerDark = Color(0xFF00504C)
val onTertiaryContainerDark = Color(0xFF9DF1EB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFE2E3D8)
val surfaceVariantDark = Color(0xFF44483D)
val onSurfaceVariantDark = Color(0xFFC5C8BA)
val outlineDark = Color(0xFF8F9285)
val outlineVariantDark = Color(0xFF44483D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3D8)
val inverseOnSurfaceDark = Color(0xFF2F312A)
val inversePrimaryDark = Color(0xFF4C662B)
val surfaceDimDark = Color(0xFF12140E)
val surfaceBrightDark = Color(0xFF383A32)
val surfaceContainerLowestDark = Color(0xFF0C0F09)
val surfaceContainerLowDark = Color(0xFF1A1C16)
val surfaceContainerDark = Color(0xFF1E201A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF33362E)

//amount
val positiveAmountLight = Color(0xFF1D9E75)
val negativeAmountLight = Color(0xFFE82D27)

val positiveAmountDark = Color(0xFF6FDBB5)
val negativeAmountDark = Color(0xFFEF7B73)

// purchase states
val overduePurchaseContentLight = Color(0xFF626364)
val overduePurchaseContainerLight = Color(0xFFF4F4F5)
val boughtPurchaseContentLight = Color(0xFF2878F8)
val boughtPurchaseContainerLight = Color(0xFFEFF4FD)
val availablePurchaseContentLight = Color(0xFF2A9E4C)
val availablePurchaseContainerLight = Color(0xFFEFF8F1)
val unreachablePurchaseContentLight = Color(0xFFEA403A)
val unreachablePurchaseContainerLight = Color(0xFFFEF0EF)
val plannedPurchaseContentLight = Color(0xFFF9B413)
val plannedPurchaseContainerLight = Color(0xFFFFFDE7)

val overduePurchaseContentDark = Color(0xFFB0B3B8)
val overduePurchaseContainerDark = Color(0xFF2A2B2D)
val boughtPurchaseContentDark = Color(0xFF8AB4F8)
val boughtPurchaseContainerDark = Color(0xFF1E2A3A)
val availablePurchaseContentDark = Color(0xFF81C995)
val availablePurchaseContainerDark = Color(0xFF1E2F25)
val unreachablePurchaseContentDark = Color(0xFFF28B82)
val unreachablePurchaseContainerDark = Color(0xFF3A1E1D)
val plannedPurchaseContentDark = Color(0xFFFFD54F)
val plannedPurchaseContainerDark = Color(0xFF3A3320)